sudo: false
language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta

cache:
  cargo: true

env:
  matrix:
    - FEATURES=
    - FEATURES=--features=blake2b --no-default-features
    - FEATURES=--features=sha2-512256,blake2b --no-default-features

# before_script:
#   - cargo +nightly install --force rustfmt-nightly

script:
  # - cargo +nightly fmt -- --write-mode=diff
  - cargo build $FEATURES
  - cargo test $FEATURES
  - cargo bench $FEATURES
  - cargo run $FEATURES -- build db README.md
  - cargo run $FEATURES -- check db README.md
  - cargo run $FEATURES -- build db2 README.md
  - "! cargo run $FEATURES -- build db README.md" # shouldn't overwrite
  - cargo run $FEATURES -- build db README.md -f # should overwrite
  - cargo run $FEATURES -- diff db db2
  - cargo run $FEATURES -- selfcheck db
