sudo: false
language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta

cache:
  cargo: true

env:
  matrix:
    - FEATURES=
    - FEATURES=--features=blake2b --no-default-features
    - FEATURES=--features=sha2-512256,blake2b,asm --no-default-features

# before_script:
#   - cargo +nightly install --force rustfmt-nightly

script:
  - ./test.sh
