sudo: false
language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta

cache:
  cargo: true

env:
  matrix:
    - FEATURES=
    - FEATURES=--features=asm

# before_script:
#   - cargo +nightly install --force rustfmt-nightly

script:
  - ./test.sh
