sudo: false
language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta

cache:
  cargo: true

env:
  matrix:
    - FEATURES=
    - FEATURES="--no-default-features --features=blake2b"
    - FEATURES="--no-default-features --features=sha2-512256,blake2b,asm"

# before_script:
#   - cargo +nightly install --force rustfmt-nightly

script:
  - ./test.sh
