[package]
name = "integrity-checker"
version = "0.1.0"
authors = ["Elliott Slaughter <elliottslaughter@gmail.com>"]

[dependencies]
clap = "2.23"
ignore = "0.2"
time = "0.1"

serde = "1.0"
serde_bytes = "0.10"
serde_cbor = "0.6"
serde_derive = "1.0"
serde_json = "1.0"

digest = "0.6"
sha2 = "0.6"
blake2 = "0.6"
