[package]
name = "integrity-checker"
version = "0.1.0"
authors = ["Elliott Slaughter <elliottslaughter@gmail.com>"]

[features]
default = []

# Hashes
blake2b = ["blake2"]

[dependencies]
clap = "2.26"
ignore = "0.2"
time = "0.1"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
base64 = "0.6"

digest = "0.6"
sha2 = "0.6"
blake2 = { version = "0.6", optional = true }
