[package]
name = "integrity-checker"
version = "0.1.0"
authors = ["Elliott Slaughter <elliottslaughter@gmail.com>"]

[dependencies]
clap = "2.21"
ignore = "0.1.9"
sha2 = "0.5"
sha3 = "0.5"
blake2 = "0.5"
