[package]
name = "integrity-checker"
version = "0.1.0"
authors = ["Elliott Slaughter <elliottslaughter@gmail.com>"]

[features]
default = []

# Hashes
blake2b = ["blake2"]

[dependencies]
clap = "2.30"
ignore = "0.4"
time = "0.1"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
base64 = "0.9"

flate2 = "1.0"

digest = "0.7"
sha2 = "0.7"
blake2 = { version = "0.7", optional = true }

[dev-dependencies]
criterion = "0.2"
tempfile = "3"

[[bench]]
name = "build"
harness = false
